<?xml version="1.0"?>
<!-- Copyright 2026 Araco Hexapod contributors -->
<!-- SPDX-License-Identifier: MIT -->
<package format="3">
  <name>araco_perception</name>
  <version>0.1.0</version>
  <description>RGB-D, IMU, and visualization configuration for Araco perception.</description>
  <maintainer email="steven060520@gmail.com">stevw</maintainer>
  <license file="LICENSE">MIT</license>

  <url type="repository">https://github.com/stevw-repo/araco-hexapod-temp</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>araco_description</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>python3-jsonschema</test_depend>
  <test_depend>python3-yaml</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
